@startuml
actor User
participant StreamingService
participant TextUI

User -> StreamingService : loginUser()

loop maks 3 forsøg
    StreamingService -> TextUI : promptText("Enter your username")
    TextUI --> User : viser prompt
    User -> TextUI : indtaster brugernavn
    TextUI --> StreamingService : username

    StreamingService -> TextUI : promptText("Enter your password")
    TextUI --> User : viser prompt
    User -> TextUI : indtaster adgangskode
    TextUI --> StreamingService : password

    alt login lykkedes
        StreamingService -> TextUI : displayMsg("Login successful")
        StreamingService -> StreamingService : showMainMenu(u)
    else forkert login
        StreamingService -> TextUI : displayMsg("Wrong username or password")
    end
end

StreamingService -> TextUI : displayMsg("Too many attempts")
StreamingService -> StreamingService : showStartMenu()

@enduml